# Generated by Django 4.2 on 2023-05-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_userprofile_address_line_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="latitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="longitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
