# Generated by Django 4.2 on 2023-05-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0003_vendor_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="slug",
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
